### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [sergioramos/remark-prism#25]
Hi!

remark is switching to a new parser internally ([micromark](https://github.com/micromark/micromark), see [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536) for more info).
From a quick glance at the code, it seems this plugin should be fine. However, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by sergioramos** [comment]
thank you for the tip, appreciated @wooorm

**Comment by sergioramos** [comment]
checking the dependency tree of this module, I see that we're using the latest version of micromark:

```
λ cat yarn.lock | grep micromark
    micromark: ~2.10.0
"micromark@npm:~2.10.0":
  resolution: "micromark@npm:2.10.1"
```

So, I can assume that it is compatible with remark 13, correct?

**Comment by wooorm** [comment]
yup!
