### ISSUE TITLE
No indentation in the latest version

### ISSUE THREAD

**Issue by Ihatetomatoes** [sergioramos/remark-prism#50]
Hi there, thanks for the cool plugin. For some reason, in the latest version (`"remark-prism": "^1.3.1"`), **the indentation is removed** when the snippet is processed by `remark-prism`.

```jsx
import remark from "remark";
import html from "remark-html";
import prism from 'remark-prism';

export default async function markdownToHtml(markdown) {
  const result = await remark().use(html).use(prism).process(markdown);
  return result.toString();
}
```
Here is the resulting HTML in the browser.

![image](https://user-images.githubusercontent.com/735672/99196378-1dbcc480-27e0-11eb-80c8-711af33b5032.png)

When I use an older version (`"remark-prism": "^1.1.14"`), the indentation is working as expected.

![image](https://user-images.githubusercontent.com/735672/99196302-a8e98a80-27df-11eb-9df6-54c9bfa0e8b1.png)

Any idea why?

FYI I am using **Next.js** with **TailwindCSS** and **statically generating posts** that include the code snippets.

**Comment by sergioramos** [comment]
One of the latest commits broke indentation, only on JSX, and I didn't catch it. I'm working on a fix.

**Comment by sergioramos** [comment]
please let me know if the latest version fixed the issue @Ihatetomatoes

**Comment by Ihatetomatoes** [comment]
Yep, all good. The latest version fixed the issue, thanks! Great work.
